# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: depviz

before:
  hooks:
    - go mod tidy

builds:
  - binary: depviz
    ldflags:
      - -s -w -X main.version={{.Version}}
    flags:
      - -trimpath
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Arch "amd64"}}CC=clang -arch x86_64{{- end }}
        {{- if eq .Arch "arm64"}}CC=clang -arch arm64{{- end }}
      - >-
        {{- if eq .Arch "amd64"}}CXX=clang++ -arch x86_64{{- end }}
        {{- if eq .Arch "arm64"}}CXX=clang++ -arch arm64{{- end }}

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  groups:
    - title: "🚀 Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "📦 Other"
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

homebrew_casks:
  - name: depviz
    repository:
      owner: jtoloui
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/jtoloui/depviz"
    description: "Visualise Go and JS/TS project dependencies as an interactive HTML map"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/depviz"]
          end
